# Generated by Django 5.0.6 on 2024-05-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task_complete_task_datecreated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
    ]
